version: "3.7"
services:

  backend:
    build: backend
    secrets:
      - db-password
    environment:
      MYSQL_HOST: db
    depends_on:
      db:
        condition: service_healthy

  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    image: mysql:8.0.19
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - /devops/mysql-service:/var/lib/mysql

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
    depends_on:
      - backend

secrets:
  db-password:
    file: db/password.txt